//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaClient.EscolaServiceAdmin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nota", Namespace="http://schemas.datacontract.org/2004/07/EscolaEntities")]
    [System.SerializableAttribute()]
    public partial class Nota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AlunoIdField;
        
        private int DisciplinaIdField;
        
        private decimal PontosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AlunoId {
            get {
                return this.AlunoIdField;
            }
            set {
                if ((this.AlunoIdField.Equals(value) != true)) {
                    this.AlunoIdField = value;
                    this.RaisePropertyChanged("AlunoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DisciplinaId {
            get {
                return this.DisciplinaIdField;
            }
            set {
                if ((this.DisciplinaIdField.Equals(value) != true)) {
                    this.DisciplinaIdField = value;
                    this.RaisePropertyChanged("DisciplinaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Pontos {
            get {
                return this.PontosField;
            }
            set {
                if ((this.PontosField.Equals(value) != true)) {
                    this.PontosField = value;
                    this.RaisePropertyChanged("Pontos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EscolaServiceAdmin.INotasServiceAdmin")]
    public interface INotasServiceAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotasServiceAdmin/AtualizarNota", ReplyAction="http://tempuri.org/INotasServiceAdmin/AtualizarNotaResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void AtualizarNota(EscolaClient.EscolaServiceAdmin.Nota nota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotasServiceAdmin/AtualizarNota", ReplyAction="http://tempuri.org/INotasServiceAdmin/AtualizarNotaResponse")]
        System.Threading.Tasks.Task AtualizarNotaAsync(EscolaClient.EscolaServiceAdmin.Nota nota);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotasServiceAdminChannel : EscolaClient.EscolaServiceAdmin.INotasServiceAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotasServiceAdminClient : System.ServiceModel.ClientBase<EscolaClient.EscolaServiceAdmin.INotasServiceAdmin>, EscolaClient.EscolaServiceAdmin.INotasServiceAdmin {
        
        public NotasServiceAdminClient() {
        }
        
        public NotasServiceAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotasServiceAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotasServiceAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotasServiceAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AtualizarNota(EscolaClient.EscolaServiceAdmin.Nota nota) {
            base.Channel.AtualizarNota(nota);
        }
        
        public System.Threading.Tasks.Task AtualizarNotaAsync(EscolaClient.EscolaServiceAdmin.Nota nota) {
            return base.Channel.AtualizarNotaAsync(nota);
        }
    }
}
